# add default minio secret for tensorboard, notebook
apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: add-minio-secret
  namespace: kubeflow-user-example-com
spec:
  desc: add minio credential
  env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          key: accesskey
          name: mlpipeline-minio-artifact
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          key: secretkey
          name: mlpipeline-minio-artifact
    - name: S3_ENDPOINT
      valueFrom:
        secretKeyRef:
          key: endpoint
          name: mlpipeline-minio-artifact
    - name: S3_USE_HTTPS
      valueFrom:
        secretKeyRef:
          key: usehttps
          name: mlpipeline-minio-artifact
    - name: S3_VERIFY_SSL
      valueFrom:
        secretKeyRef:
          key: verifyssl
          name: mlpipeline-minio-artifact
  selector:
    matchLabels:
      access-tb: 'true'