kubeflowManifestsRepoBranch: v1.9.1-branch
resources:
  clusterLocalGateway:
    path: common/istio-1-22/cluster-local-gateway/base
  istioCrds:
    path: common/istio-1-22/istio-crds/base
  istioInstall:
    path: common/istio-1-22/istio-install/overlays/oauth2-proxy
  istioNamespace:
    path: common/istio-1-22/istio-namespace/base
  istioResources:
    path: common/istio-1-22/kubeflow-istio-resources/base
  certManagerBase:
    path: common/cert-manager/cert-manager/base
  kserve:
    path: contrib/kserve/kserve
  kserveModelsWebApp:
    path: contrib/kserve/models-web-app/overlays/kubeflow
  #use local dex + external (kuber) tokens, see https://github.com/kubeflow/manifests/pull/2864
  oauth2Proxy:
    path: common/oauth2-proxy/overlays/m2m-dex-and-kind
  pipelines:
    kustomize:
      images:
        - >-
          gcr.io/ml-pipeline/minio=quay.io/minio/minio:RELEASE.2021-12-29T06-49-06Z
      patches:
        - target:
            kind: Deployment
            name: minio
          patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/args
              value:
                - server
                - '--console-address'
                - ':9001'
                - /data
        # apply fix https://github.com/kubeflow/pipelines/pull/11403/commits/e94d260da967d1e781b35bd076e1c61450d7b0bb
        - patch: |-
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: ml-pipeline-ui
            spec:
              template:
                spec:
                  containers:
                  - name: ml-pipeline-ui
                    env:
                      - name: DISABLE_GKE_METADATA
                        value: 'true'