kubeflowManifestsRepoBranch: v1.9.1-branch
resources:
  clusterLocalGateway:
    path: common/istio-1-22/cluster-local-gateway/base
  istioCrds:
    path: common/istio-1-22/istio-crds/base
  istioInstall:
    path: common/istio-1-22/istio-install/overlays/oauth2-proxy
  istioNamespace:
    path: common/istio-1-22/istio-namespace/base
  istioResources:
    path: common/istio-1-22/kubeflow-istio-resources/base
  certManagerBase:
    path: common/cert-manager/cert-manager/base
  knativeServing:
    kustomize:
      patches:
        # https://kserve.github.io/website/latest/modelserving/nodescheduling/inferenceservicenodescheduling/
        - patch: |-
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: config-features
              namespace: knative-serving
            data:
              kubernetes.podspec-nodeselector: "enabled"
        # https://kserve.github.io/website/0.15/modelserving/v1beta1/triton/bert/#setup
        - patch: |-
            apiVersion: v1
            kind: ConfigMap
            metadata:
              name: config-deployment
              namespace: knative-serving
            data:
              registriesSkippingTagResolving: "nvcr.io"

        # setup clean old revisions
        - target:
            kind: ConfigMap
            name: config-gc
          patch: |-
            - op: replace
              path: /data
              value:
                max-non-active-revisions: '0'
                min-non-active-revisions: '0'
                retain-since-create-time: disabled
                retain-since-last-active-time: disabled
  kserve:
    path: contrib/kserve/kserve
    kustomize:
      # replace old tensorflow
      # https://github.com/triton-inference-server/server/releases/tag/v2.46.0
      images:
        - tensorflow/serving:2.15.1
        #see https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html#framework-matrix-2025__section_zz3_hdz_m1c
        # tensoflow not supported from 25.03-py3
        # tensorrt 8.6.1.6 https://github.com/triton-inference-server/server/releases/tag/v2.44.0 supported by
        # kubeflownotebookswg/jupyter-tensorflow-cuda-full:latest kubeflow notebook
        - nvcr.io/nvidia/tritonserver:24.12-py3
      patches:
        # setup clean old revisions
        - target:
            kind: ConfigMap
            name: inferenceservice-config
          patch: |-
            - op: replace
              path: /data/agent
              value: |-
                {
                    "image" : "ghcr.io/ptishkin/kserve-agent-probe/agent:latest",
                    "memoryRequest": "100Mi",
                    "memoryLimit": "1Gi",
                    "cpuRequest": "100m",
                    "cpuLimit": "1"
                }

  kserveModelsWebApp:
    path: contrib/kserve/models-web-app/overlays/kubeflow
  #use local dex + external (kuber) tokens, see https://github.com/kubeflow/manifests/pull/2864
  oauth2Proxy:
    path: common/oauth2-proxy/overlays/m2m-dex-and-kind
  pipelines:
    repoBranchOverride: master
    path: applications/pipeline/upstream/env/cert-manager/platform-agnostic-multi-user
    kustomize:
      # replace old minio (on 2019 - memory leaks on ubuntu 22.04)
      images:
        - >-
          gcr.io/ml-pipeline/minio=quay.io/minio/minio:RELEASE.2021-12-29T06-49-06Z
      patches:
        - patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/volumeMounts
              value:
                - mountPath: /data
                  name: data
          target:
            kind: Deployment
            name: minio
        # open console port (web ui)
        - patch: |-
            - op: replace
              path: /spec/template/spec/containers/0/args
              value:
                - server
                - '--console-address'
                - ':9001'
                - /data
          target:
            kind: Deployment
            name: minio
        # apply fix https://github.com/kubeflow/pipelines/pull/11403/commits/e94d260da967d1e781b35bd076e1c61450d7b0bb
        - patch: |-
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: ml-pipeline-ui
            spec:
              template:
                spec:
                  containers:
                  - name: ml-pipeline-ui
                    env:
                      - name: DISABLE_GKE_METADATA
                        value: 'true'

raw:
  resources:
    minio-kserve-tensorboard-secret:
      #redefine default secret for kserve / tensorboard minio access
      apiVersion: v1
      kind: Secret
      spec:
        metadata:
          name: minio-kserve-tensorboard-secret
          namespace: kubeflow-user-example-com
          annotations:
            serving.kserve.io/s3-endpoint: minio-service.kubeflow:9000
            serving.kserve.io/s3-useanoncredential: 'false'
            serving.kserve.io/s3-usehttps: '0'
            serving.kserve.io/s3-region: 'minio'
            serving.kserve.io/s3-usevirtualbucket: "false"
        data:
          AWS_ACCESS_KEY_ID: bWluaW8=
          AWS_SECRET_ACCESS_KEY: bWluaW8xMjM=
          S3_ENDPOINT: bWluaW8tc2VydmljZS5rdWJlZmxvdzo5MDAw
          S3_USE_HTTPS: MA==
          S3_VERIFY_SSL: MQ==
          S3_REGION: bWluaW8=

    minio-kserve-sa:
      #add sa for https://kserve.github.io/website/0.8/sdk_docs/docs/V1beta1PredictorSpec/#properties service_account_name
      apiVersion: v1
      kind: ServiceAccount
      spec:
        metadata:
          name: minio-kserve-sa
          namespace: kubeflow-user-example-com
        secrets:
          - name: minio-kserve-tensorboard-secret

    minio-tensorboard-access:
      # add minio access for tensorboard
      apiVersion: kubeflow.org/v1alpha1
      kind: PodDefault
      spec:
        metadata:
          name: tensorboard-minio-access
          namespace: kubeflow-user-example-com
        spec:
          desc: TensorBoard minio access (add-minio-secret)
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: minio-kserve-tensorboard-secret
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: minio-kserve-tensorboard-secret
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  key: S3_ENDPOINT
                  name: minio-kserve-tensorboard-secret
            - name: S3_USE_HTTPS
              valueFrom:
                secretKeyRef:
                  key: S3_USE_HTTPS
                  name: minio-kserve-tensorboard-secret
            - name: S3_VERIFY_SSL
              valueFrom:
                secretKeyRef:
                  key: S3_VERIFY_SSL
                  name: minio-kserve-tensorboard-secret
          selector:
            matchLabels:
              minio-tensorboard-access: 'true'

    minio-mlpipeline-access:
      # add default sa to connect notebook with pipelines
      apiVersion: kubeflow.org/v1alpha1
      kind: PodDefault
      spec:
        metadata:
          name: minio-mlpipeline-access
          namespace: kubeflow-user-example-com
        spec:
          desc: Notebook allow access to Kubeflow Pipelines (access-ml-pipeline)
          env:
            - name: KF_PIPELINES_SA_TOKEN_PATH
              value: /var/run/secrets/kubeflow/pipelines/token
          volumeMounts:
            - mountPath: /var/run/secrets/kubeflow/pipelines
              name: volume-kf-pipeline-token
              readOnly: true
          volumes:
            - name: volume-kf-pipeline-token
              projected:
                sources:
                  - serviceAccountToken:
                      audience: pipelines.kubeflow.org
                      expirationSeconds: 7200
                      path: token
          selector:
            matchLabels:
              minio-mlpipeline-access: 'true'

    tcp-gateway-service:
      apiVersion: v1
      kind: Service
      spec:
        metadata:
          name: tcp-gateway-service
          namespace: istio-system
        spec:
          internalTrafficPolicy: Cluster
          ipFamilies:
            - IPv4
          ipFamilyPolicy: SingleStack
          ports:
            - name: http2
              port: 9001
              protocol: TCP
              targetPort: 9001
            - name: tcp-minio
              port: 9002
              protocol: TCP
              targetPort: 9002
            - name: tcp-mysql
              port: 3306
              protocol: TCP
              targetPort: 3306
          selector:
            app: cluster-local-gateway
            istio: cluster-local-gateway
          sessionAffinity: None
          type: ClusterIP

    http-gateway:
      #open minio access without dex into console port via istio
      apiVersion: networking.istio.io/v1
      kind: Gateway
      spec:
        metadata:
          name: http-gateway
          namespace: kubeflow
        spec:
          selector:
            app: cluster-local-gateway
            istio: cluster-local-gateway
          servers:
            - hosts:
                - '*'
              port:
                name: http
                number: 9001
                protocol: HTTP

    http-minio-vservice:
      apiVersion: networking.istio.io/v1
      kind: VirtualService
      spec:
        metadata:
          name: http-minio-vservice
          namespace: kubeflow
        spec:
          gateways:
            - http-gateway
          hosts:
            - '*'
          http:
            - route:
                - destination:
                    host: tcp-minio-console-service.kubeflow.svc.cluster.local
                    port:
                      number: 9001
              timeout: 300s

    tcp-gateway:
      apiVersion: networking.istio.io/v1
      kind: Gateway
      spec:
        metadata:
          name: tcp-gateway
          namespace: kubeflow
        spec:
          selector:
            app: cluster-local-gateway
            istio: cluster-local-gateway
          servers:
            - hosts:
                - '*'
              port:
                name: tcp-vservice-minio
                number: 9002
                protocol: TCP
            - hosts:
                - '*'
              port:
                name: tcp-vservice-mysql
                number: 3306
                protocol: TCP

    tcp-vservice:
      apiVersion: networking.istio.io/v1
      kind: VirtualService
      spec:
        metadata:
          name: tcp-vservice
          namespace: kubeflow
        spec:
          gateways:
            - tcp-gateway
          hosts:
            - '*'
          tcp:
            - match:
                - port: 3306
              route:
                - destination:
                    host: mysql.kubeflow.svc.cluster.local
                    port:
                      number: 3306
            - match:
                - port: 9002
              route:
                - destination:
                    host: tcp-minio-console-service.kubeflow.svc.cluster.local
                    port:
                      number: 9001

    tcp-minio-console-service:
      #open new port for 2021 minio build, via tcp-gateway-service:80,9002 =>
      # [cluster-local-gateway:9001 => http-gateway:9001 => http-minio-vservice:9001]
      # [cluster-local-gateway:9002 => tcp-gateway:9002 => tcp-vservice:9002]
      # => tcp-minio-console-service:9001
      apiVersion: v1
      kind: Service
      spec:
        metadata:
          name: tcp-minio-console-service
          namespace: kubeflow
        spec:
          internalTrafficPolicy: Cluster
          ipFamilies:
            - IPv4
          ipFamilyPolicy: SingleStack
          ports:
            - name: 9001tcp
              port: 9001
              protocol: TCP
              targetPort: 9001
          selector:
            app: minio
            application-crd-id: kubeflow-pipelines
          sessionAffinity: None
          type: ClusterIP
