apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-monitoring-crd
  namespace: {{ .Values.argoNamespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
{{- $labels := merge (.Values.commonAppLabels | default (dict)) (default (dict)) }}
  {{- if $labels }}
  labels: 
{{ toYaml $labels | indent 4 }}
  {{- end }}
{{- $annotations := merge (.Values.commonAppAnnotations | default (dict)) (default (dict)) }}
{{- if $annotations }}
  annotations:
{{ toYaml $annotations | indent 4 }}
{{- end }}
spec:
  destination:
    namespace: cattle-monitoring-system
    name: {{ .Values.destinationServer }}
  project: {{ .Values.argoProjectName }}
  source:
    # Chart from Chart Repo
    chart: rancher-monitoring-crd
    repoURL: {{ .Values.rancherManifestsRepo}}
    targetRevision: {{ .Values.rancherManifestsRepoBranch }}

{{ toYaml .Values.defaultAppSpec | indent 2 }}