#install https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_app_create/
#argocd app create guestbook --file <path-to-yaml-file>
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-monitoring
  namespace: {{ .Values.argoNamespace }}
{{- $annotations := merge (.Values.commonAppAnnotations | default (dict)) (default (dict)) }}
{{- if $annotations }}
  annotations:
{{ toYaml $annotations | indent 4 }}
{{- end }}
spec:
  destination:
    namespace: cattle-monitoring-system
    name: in-cluster
  project: {{ .Values.argoProjectName }}
  #https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
  sources:
    # Chart from Chart Repo
    - chart: rancher-monitoring
      repoURL: {{ .Values.rancherManifestsRepo}}
      targetRevision: {{ .Values.rancherManifestsRepoBranch }}
      helm:
        valueFiles:
        - $upvalues/rancher/charts/rancher-monitoring/valuesup.yaml
        values: |
{{ toYaml .Values.raw | indent 10 }}

    # Values from Git
    - repoURL: 'https://github.com/ptishkin/argocd.git'
      targetRevision: rancher
      name: custom
      ref: upvalues

{{- $appSpec := deepCopy (.Values.defaultAppSpec | default (dict)) | merge (.Values.clientAppSpec | default (dict)) }}
{{ toYaml $appSpec | indent 2 }}