#install https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_app_create/
#argocd app create guestbook --file <path-to-yaml-file>
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-monitoring
  namespace: {{ .Values.argoNamespace }}
{{- $labels := merge (.Values.commonLabels | default (dict)) (default (dict)) }}
  {{- if $labels }}
  labels: 
{{ toYaml $labels | indent 4 }}
  {{- end }}
{{- $annotations := merge (.Values.commonAppAnnotations | default (dict)) (default (dict)) }}
{{- if $annotations }}
  annotations:
{{ toYaml $annotations | indent 4 }}
{{- end }}
spec:
  destination:
    namespace: cattle-monitoring-system
    name: {{ .Values.destinationServer }}
  project: {{ .Values.argoProjectName }}
  #https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
  source:
    # Chart from Chart Repo
    chart: rancher-monitoring
    repoURL: {{ .Values.rancherManifestsRepo}}
    targetRevision: {{ .Values.rancherManifestsRepoBranch }}
    helm:
      parameters:
        - name: prometheus.prometheusSpec.resources.limits.cpu
          value: 2000m
        - name: prometheus.prometheusSpec.resources.limits.memory
          value: 6000Mi
        
        # https://github.com/rancher/dashboard/blob/release-2.10/shell/chart/monitoring/ClusterSelector.vue#L68C71-L68C78
        - name: rkeControllerManager.enabled
          value: 'true'
        - name: rkeEtcd.enabled
          value: 'true'
        - name: rkeProxy.enabled
          value: 'true'
        - name: rkeScheduler.enabled
          value: 'true'
      values: |
{{ toYaml .Values.raw | indent 8 }}

{{- $appSpec := deepCopy (.Values.defaultAppSpec | default (dict)) | merge (.Values.clientAppSpec | default (dict)) }}
{{ toYaml $appSpec | indent 2 }}