#install https://argo-cd.readthedocs.io/en/stable/user-guide/commands/argocd_app_create/
#argocd app create guestbook --file <path-to-yaml-file>
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-monitoring
  namespace: argocd
spec:
  destination:
    namespace: cattle-monitoring-system
    name: in-cluster
  project: default
  #https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
  sources:
    # Chart from Chart Repo
    - repoURL: https://charts.rancher.io/
      chart: rancher-monitoring
      targetRevision: 105.2.1+up66.7.1-rancher.14
      helm:
        valueFiles:
        - $upvalues/rancher/charts/rancher-monitoring/valuesup.yaml
    # Values from Git
    - repoURL: 'https://github.com/ptishkin/argocd.git'
      targetRevision: rancher
      name: custom
      ref: upvalues