argoProjectName: rancher-monitoring
argoNamespace: argocd
commonAppAnnotations: {}
commonAppLabels: {}
destinationServer: in-cluster
rancherManifestsRepo: https://charts.rancher.io/
rancherManifestsRepoBranch: 105.2.1+up66.7.1-rancher.14

defaultAppSpec:
  ignoreDifferences:
  - group: argoproj.io
    jsonPointers:
    - /status
    kind: Application
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 20s
        factor: 1
        maxDuration: 20s
      limit: 30
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
    - CreateNamespace=true
    - Prune=true

clientAppSpec:
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=false
    - CreateNamespace=true
    - Prune=true

raw:
  global:
    cattle:
      systemDefaultRegistry: ''
      clusterId: ''
      clusterName: ''
      systemProjectId: ''
      url: ''

  prometheus:
    prometheusSpec:
      storageSpec:
        disableMountSubPath: true
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: local-path

  grafana:
    persistence:
      accessModes:
        - ReadWriteOnce
      enabled: true
      size: 3Gi
      storageClassName: local-path
      subPath: null
      type: statefulset